"""
This code was generated by Claude AI.

prompts:

1) 
Can you write some python code to visualize a json that includes document clusters. 
The json format is: `{"title": "<article_title>", "category1": "<name>:<probability>", "category2":
"<name>:<probability>", "category3": "<name>:<probability>", "confidence": "<low|medium|high>",
"difficulty": "<beginner|intermediate|advanced|expert>", "prior_knowledge": "<range between 0 and 1>"}`

2) 
The new json format is `{
    "title": "<article_title>",
    "<category1>": "<probability>",
    "<category2>": "<probability>",
    "<category3>": "<probability>",
    "confidence": "<low|medium|high>",
    "difficulty": "<beginner|intermediate|advanced|expert>",
    "prior_knowledge": "<float between 0 and 1>"
}` Please adjust the code accordingly

3) 
The new json format includes `"tokens": "<number_of_tokens>`, update the dashboard 
to include the distribution of document sizes for each primary category

4) 
Can you update `visualize_clusters.py` to plot the distribution of difficulties for each category?

visualize_clusters.py

Visualizes document-cluster JSON records of the form:

{
    "title": "<article_title>",
    "<category1>": "<probability>",
    "<category2>": "<probability>",
    "<category3>": "<probability>",
    "confidence": "<low|medium|high>",
    "difficulty": "<beginner|intermediate|advanced|expert>",
    "prior_knowledge": "<float between 0 and 1>",
    "tokens": "<number_of_tokens>",
    "vocab_complexity": "<complexity>",
    "sentence_quality": "<sentence_quality>"
}

Category names are now arbitrary JSON keys (e.g. "machine_learning": "0.82")
rather than fixed "category1"/"category2"/"category3" fields. Any key that
isn't title/confidence/difficulty/prior_knowledge/tokens is treated as a
category, and a document can have any number of them - not just 3.

Input file can be:
  - a JSON array of such records, or
  - a single JSON object (one record), or
  - a JSON-lines file (one record per line)

Usage:
    python visualize_clusters.py records.json
    python visualize_clusters.py records.json --out dashboard.png
"""

import argparse
import json
from collections import Counter

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

CONFIDENCE_ORDER = ["low", "medium", "high"]
DIFFICULTY_ORDER = ["beginner", "intermediate", "advanced", "expert"]

CONFIDENCE_COLORS = {"low": "#E07B54", "medium": "#F2C14E", "high": "#5B8C5A"}

# Sequential color scale for difficulty (ordinal: beginner -> expert). Shared
# by the overall difficulty bar chart and the per-category breakdown below.
DIFFICULTY_COLORS = {
    "beginner": "#cfe8ff",
    "intermediate": "#7fb8e8",
    "advanced": "#3a78b5",
    "expert": "#0d2c54",
}

# Every other key on a record is treated as "<category_name>": "<probability>"
RESERVED_KEYS = {"title", "confidence", "difficulty", "prior_knowledge", "tokens", "vocab_complexity", "sentence_quality", "batch_id"}
_RESERVED_KEYS_NORM = {k.lower().replace(" ", "_").replace("-", "_")
                       for k in RESERVED_KEYS}



# ---------------------------------------------------------------------------
# Loading & parsing
# ---------------------------------------------------------------------------

def load_records(path):
    """Load records from a JSON array, a single JSON object, or JSON-lines."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read().strip()

    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return [data]
        if isinstance(data, list):
            return data
    except json.JSONDecodeError:
        pass

    # Fall back to JSON-lines (one object per line)
    records = []
    for line in text.splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records


def parse_probability(value):
    """Coerce a probability field (often a string) into a float, or None."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def parse_int(value):
    """Coerce a count field (often a string, sometimes "1234.0") into an
    int, or None."""
    if value is None or value == "":
        return None
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None
    

def normalise_category_name(name):
    """Canonical form for a category name: lowercase, whitespace/hyphens/dots
    replaced with underscores, leading/trailing whitespace stripped, runs of
    underscores collapsed to one.
 
    "Machine Learning", "machine-learning", "Machine_Learning", and
    "machine_learning" all map to "machine_learning" so they're treated as
    the same category even when spelled differently across records."""
    import re
    name = str(name).strip().lower()
    name = re.sub(r"[\s\-\.]+", "_", name)   # spaces / hyphens / dots → _
    name = re.sub(r"_+", "_", name)           # collapse repeated underscores
    name = name.strip("_")                    # remove leading/trailing _
    return name


def parse_records(records):
    """Turn raw JSON records into a flat list of dicts ready for plotting.

    Each result has a "categories" dict of {category_name: probability},
    sorted from most to least probable, so "rank 0" is always the
    document's primary category regardless of how many it has."""
    parsed = []
    for r in records:
        item = {
            "title": r.get("title", "Untitled"),
            "confidence": (r.get("confidence") or "unknown").lower(),
            "difficulty": (r.get("difficulty") or "unknown").lower(),
            "prior_knowledge": parse_probability(r.get("prior_knowledge")),
            "tokens": parse_int(r.get("tokens")),
            "location": r.get("location", "None"),
            "vocab_complexity": parse_probability(r.get("vocab_complexity")),
            "sentence_quality": parse_probability(r.get("sentence_quality")),
        }

        categories = {}
        for key, value in r.items():
            if normalise_category_name(key) in _RESERVED_KEYS_NORM:
                continue
            prob = parse_probability(value)
            if prob is None:
                continue
            norm_key = normalise_category_name(key)
            # When two raw keys normalise to the same name, keep the higher
            # probability rather than silently discarding one or summing
            # (which could exceed 1.0).
            if norm_key not in categories or prob > categories[norm_key]:
                categories[norm_key] = prob
 
        item["categories"] = dict(
            sorted(categories.items(), key=lambda kv: kv[1], reverse=True)
        )
        parsed.append(item)
    return parsed



def category_at_rank(item, rank):
    """Return (name, probability) for the rank-th most probable category
    on this document (rank 0 = highest probability), or (None, None)."""
    entries = list(item["categories"].items())
    if rank < len(entries):
        return entries[rank]
    return None, None


def top_category(item):
    """Convenience wrapper: a document's single most probable category."""
    return category_at_rank(item, 0)


# ---------------------------------------------------------------------------
# Individual panel plots
# ---------------------------------------------------------------------------

def primary_category_counts(parsed):
    """How many documents have each category as their top (highest
    probability) pick. Shared by the bar chart and the token-length panel
    so both agree on which categories are "top" and in what order."""
    counter = Counter()
    for p in parsed:
        name, _ = top_category(p)
        if name:
            counter[name] += 1
    return counter


def plot_top_categories(parsed, ax, top_n=10):
    counter = primary_category_counts(parsed)
    common = counter.most_common(top_n)
    if not common:
        ax.axis("off")
        return
    names, counts = zip(*common)
    y = range(len(names))
    ax.barh(y, counts, color="#4C72B0")
    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.invert_yaxis()
    ax.set_xlabel("Document count")
    ax.set_title("Top primary categories")


def plot_confidence_distribution(parsed, ax):
    counter = Counter(p["confidence"] for p in parsed)
    order = [c for c in CONFIDENCE_ORDER if c in counter]
    order += [c for c in counter if c not in CONFIDENCE_ORDER]
    counts = [counter[c] for c in order]
    colors = [CONFIDENCE_COLORS.get(c, "#999999") for c in order]
    ax.bar(order, counts, color=colors)
    ax.set_title("Confidence distribution")
    ax.set_ylabel("Document count")


def plot_difficulty_distribution(parsed, ax):
    counter = Counter(p["difficulty"] for p in parsed)
    order = [d for d in DIFFICULTY_ORDER if d in counter]
    order += [d for d in counter if d not in DIFFICULTY_ORDER]
    counts = [counter[d] for d in order]
    colors = [DIFFICULTY_COLORS.get(d, "#999999") for d in order]
    ax.bar(order, counts, color=colors)
    ax.set_title("Difficulty distribution")
    ax.set_ylabel("Document count")
    ax.tick_params(axis="x", rotation=20)


def plot_prior_knowledge_vs_difficulty(parsed, ax):
    diff_x = {d: i for i, d in enumerate(DIFFICULTY_ORDER)}
    rng = np.random.default_rng(0)

    for p in parsed:
        if p["prior_knowledge"] is None or p["difficulty"] not in diff_x:
            continue
        x = diff_x[p["difficulty"]] + rng.uniform(-0.15, 0.15)
        y = p["prior_knowledge"]
        color = CONFIDENCE_COLORS.get(p["confidence"], "#999999")
        ax.scatter(x, y, color=color, alpha=0.75, s=45,
                   edgecolor="white", linewidth=0.5)

    ax.set_xticks(range(len(DIFFICULTY_ORDER)))
    ax.set_xticklabels(DIFFICULTY_ORDER, rotation=20)
    ax.set_ylim(-0.05, 1.05)
    ax.set_ylabel("Prior knowledge")
    ax.set_title("Prior knowledge vs. difficulty\n(color = confidence)")

    handles = [mpatches.Patch(color=c, label=l) for l, c in CONFIDENCE_COLORS.items()]
    ax.legend(handles=handles, title="Confidence", fontsize=8, loc="upper right")


def plot_category_probability_box(parsed, ax, max_ranks=5):
    """Box-plots probability by rank (rank 0 = each doc's top category,
    rank 1 = second, etc.), since documents may not all carry the same
    number of categories anymore."""
    max_present = max((len(p["categories"]) for p in parsed), default=0)
    n_ranks = min(max_present, max_ranks)

    data, labels = [], []
    for rank in range(n_ranks):
        vals = [prob for p in parsed
                for _, prob in [category_at_rank(p, rank)] if prob is not None]
        if vals:
            data.append(vals)
            labels.append(f"rank {rank + 1}")

    if not data:
        ax.axis("off")
        return
    try:
        ax.boxplot(data, tick_labels=labels)  # matplotlib >= 3.9
    except TypeError:
        ax.boxplot(data, labels=labels)  # matplotlib < 3.9
    ax.set_ylabel("Probability")
    ax.set_title("Probability spread by category rank\n(rank 1 = each doc's top category)")


def plot_tokens_by_category(parsed, ax, top_n=10):
    """Box-plots document length (tokens) for each of the most common
    primary categories, so you can see e.g. whether "history" articles run
    much longer than "mathematics" articles. Uses the same top-N category
    selection/order as plot_top_categories for easy cross-reference."""
    counter = primary_category_counts(parsed)
    top_names = [name for name, _ in counter.most_common(top_n)]

    # Precompute (top category, tokens) once per doc rather than re-deriving
    # top_category() inside a nested loop over every candidate category.
    doc_top_tokens = [(top_category(p)[0], p["tokens"]) for p in parsed]

    data, labels = [], []
    for name in top_names:
        vals = [tok for cat, tok in doc_top_tokens if cat == name and tok is not None]
        if vals:
            data.append(vals)
            labels.append(name)

    if not data:
        ax.axis("off")
        return
    try:
        ax.boxplot(data, tick_labels=labels, vert=False)  # matplotlib >= 3.9
    except TypeError:
        ax.boxplot(data, labels=labels, vert=False)  # matplotlib < 3.9
    ax.invert_yaxis()  # largest/most common category on top, matching the bar chart
    ax.set_xlabel("Tokens (document length)")
    ax.set_title(f"Document length by top {len(labels)} categories")


def plot_difficulty_by_category(parsed, ax, top_n=10):
    """100%-stacked horizontal bars: for each of the most common primary
    categories, what share of its documents are beginner/intermediate/
    advanced/expert. Normalized per-category (each bar sums to 100%)
    rather than raw counts, since the question is "what's the difficulty
    mix *within* this category", not how many documents it has overall
    (that's already covered by plot_top_categories). Uses the same top-N
    category selection/order as plot_top_categories for cross-reference."""
    counter = primary_category_counts(parsed)
    top_names = [name for name, _ in counter.most_common(top_n)]

    doc_top_difficulty = [(top_category(p)[0], p["difficulty"]) for p in parsed]

    rows = []
    for name in top_names:
        diffs = [d for cat, d in doc_top_difficulty if cat == name]
        if not diffs:
            continue
        diff_counts = Counter(diffs)
        total = len(diffs)
        shares = [diff_counts.get(d, 0) / total for d in DIFFICULTY_ORDER]
        rows.append((name, shares, total))

    if not rows:
        ax.axis("off")
        return

    names = [r[0] for r in rows]
    totals = [r[2] for r in rows]
    y = np.arange(len(names))
    left = np.zeros(len(names))
    for i, d in enumerate(DIFFICULTY_ORDER):
        widths = np.array([r[1][i] for r in rows])
        ax.barh(y, widths, left=left, color=DIFFICULTY_COLORS.get(d, "#999999"),
                label=d, height=0.7)
        left += widths

    for yi, total in zip(y, totals):
        ax.text(1.02, yi, f"n={total}", va="center", fontsize=7, transform=ax.get_yaxis_transform())

    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.invert_yaxis()
    ax.set_xlim(0, 1)
    ax.set_xlabel("Share of documents")
    ax.set_title(f"Difficulty mix within top {len(names)} categories")
    ax.legend(title="Difficulty", fontsize=7, loc="lower left",
              bbox_to_anchor=(0, -0.32), ncol=4, framealpha=0.9)


def plot_quality_metrics_by_category(parsed, ax, top_n=10):
    """Grouped box plots of prior_knowledge, vocab_complexity, and
    sentence_quality for each of the top-N primary categories, so these
    three continuous quality signals can be compared side by side across
    a handful of the most common topics. Uses the same top-N category
    selection/order as plot_top_categories for cross-reference."""
    counter = primary_category_counts(parsed)
    top_names = [name for name, _ in counter.most_common(top_n)]

    metrics = [
        ("prior_knowledge", "#4C72B0"),
        ("vocab_complexity", "#DD8452"),
        ("sentence_quality", "#55A868"),
    ]
    box_width = 0.8 / len(metrics)

    doc_top = [(top_category(p)[0], p) for p in parsed]

    present_names = []
    data_by_metric = {m: [] for m, _ in metrics}
    positions_by_metric = {m: [] for m, _ in metrics}
    for name in top_names:
        docs = [p for cat, p in doc_top if cat == name]
        if not docs:
            continue
        base = len(present_names)
        present_names.append(name)
        for mi, (metric, _) in enumerate(metrics):
            vals = [p[metric] for p in docs if p[metric] is not None]
            data_by_metric[metric].append(vals)
            offset = (mi - (len(metrics) - 1) / 2) * box_width
            positions_by_metric[metric].append(base + offset)

    if not present_names:
        ax.axis("off")
        return

    for metric, color in metrics:
        pairs = [(vals, pos) for vals, pos in
                 zip(data_by_metric[metric], positions_by_metric[metric]) if vals]
        if not pairs:
            continue
        vals, positions = zip(*pairs)
        bp = ax.boxplot(vals, positions=positions, widths=box_width * 0.85,
                         patch_artist=True, showfliers=False)
        for box in bp["boxes"]:
            box.set_facecolor(color)
            box.set_alpha(0.7)
        for median in bp["medians"]:
            median.set_color("black")

    ax.set_xticks(range(len(present_names)))
    ax.set_xticklabels(present_names, rotation=45, ha="right")
    ax.set_xlim(-0.6, len(present_names) - 0.4)
    ax.set_ylim(-0.05, 1.05)
    ax.set_ylabel("Score")
    ax.set_title(f"Quality metric spread across top {len(present_names)} categories")

    handles = [mpatches.Patch(color=c, label=m.replace("_", " ")) for m, c in metrics]
    ax.legend(handles=handles, fontsize=7, loc="upper right")


def plot_summary_text(parsed, ax, fig):
    ax.axis("off")
    n = len(parsed)
    avg_pk = np.mean([p["prior_knowledge"] for p in parsed if p["prior_knowledge"] is not None])
    avg_tokens = np.mean([p["tokens"] for p in parsed if p["tokens"] is not None])
    n_categories = len({top_category(p)[0] for p in parsed if top_category(p)[0]})
    lines = [
        f"Documents: {n}",
        f"Distinct primary categories: {n_categories}",
        f"Avg. prior knowledge: {avg_pk:.2f}" if not np.isnan(avg_pk) else "Avg. prior knowledge: n/a",
        f"Avg. tokens: {avg_tokens:.0f}" if not np.isnan(avg_tokens) else "Avg. tokens: n/a",
    ]
    # ax.text(0.05, 0.8, "\n".join(lines), fontsize=12, va="top",
            # family="monospace", transform=ax.transAxes)
    fig.supxlabel(' | '.join(lines))
    ax.set_title("Summary")


# ---------------------------------------------------------------------------
# Dashboard assembly
# ---------------------------------------------------------------------------

def build_dashboard(parsed, out_path):
    fig, axes = plt.subplots(3, 3, figsize=(20, 14))

    plot_top_categories(parsed, axes[0, 0])
    plot_confidence_distribution(parsed, axes[0, 1])
    plot_difficulty_distribution(parsed, axes[0, 2])
    plot_tokens_by_category(parsed, axes[1, 0])
    plot_prior_knowledge_vs_difficulty(parsed, axes[1, 1])
    plot_category_probability_box(parsed, axes[1, 2])
    plot_difficulty_by_category(parsed, axes[2, 0])
    plot_quality_metrics_by_category(parsed, axes[2, 1])
    plot_summary_text(parsed, axes[2, 2], fig)

    fig.suptitle("Document Cluster Overview", fontsize=16, fontweight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved dashboard to {out_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Visualize document cluster JSON")
    parser.add_argument("json_path", help="Path to input JSON (array, single object, or JSON-lines)")
    parser.add_argument("--out", default="cluster_dashboard.png", help="Output image path")
    args = parser.parse_args()

    records = load_records(args.json_path)
    parsed = parse_records(records)

    if not parsed:
        raise SystemExit("No records found in the input file.")

    build_dashboard(parsed, args.out)


if __name__ == "__main__":
    main()
