"""
This code was generated by Claude AI.

prompts: 

1) 
Can you include some code for a undirected graph visualization 
to see exactly how close documents are to each other?

2)
Hi Claude the document similarity graph is unreadable with >=1000 documents
[includes image of unreadable graph]

3)
Looks good. Can you draw circles around the clusters and label them with the primary category?

document_similarity_graph.py

Builds an undirected graph showing how "close" documents are to one another,
based on the categories (and probabilities) assigned to each document by the
clustering pipeline. Categories are dynamic JSON keys (e.g.
"machine_learning": "0.82") rather than fixed category1/2/3 fields, and a
document can have any number of them. Two documents are considered close if
they share categories with similar weight - this is measured with cosine
similarity over a "category vector" for each document.

Scales from a handful of documents up to several thousand: layout switches
to ForceAtlas2 (much better at separating clusters than spring layout at
scale), node/edge sizing shrinks automatically as the document count grows,
and labels are reduced to one representative title per detected community
once there are more documents than would fit legibly - rather than printing
every single title on top of each other. A dashed circle is drawn around
each detected cluster and labeled with its primary category (the category
most often the top pick among that cluster's documents).

Requires: networkx, matplotlib, numpy
Reuses the JSON loading/parsing from visualize_clusters.py (keep both files
in the same folder).

Usage:
    python document_similarity_graph.py records.json
    python document_similarity_graph.py records.json --method knn --k 3
    python document_similarity_graph.py records.json --method threshold --threshold 0.2
    python document_similarity_graph.py records.json --color-by community
    python document_similarity_graph.py records.json --max-labels 60
    python document_similarity_graph.py records.json --no-cluster-circles
    python document_similarity_graph.py records.json --min-circle-size 5
"""

import argparse
import textwrap
from collections import Counter, defaultdict

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

from visualize_clusters import (
    DIFFICULTY_ORDER,
    load_records,
    parse_records,
)


# ---------------------------------------------------------------------------
# Build a category vector per document, then cosine-similarity between docs
# ---------------------------------------------------------------------------

def build_vocab(parsed):
    """Collect the set of all distinct category names across all documents."""
    vocab = set()
    for p in parsed:
        vocab.update(p["categories"].keys())
    return sorted(vocab)


def build_matrix(parsed, vocab):
    """Rows = documents, columns = categories, values = assigned probability
    (0 if a document was not assigned that category)."""
    index = {name: i for i, name in enumerate(vocab)}
    matrix = np.zeros((len(parsed), len(vocab)))
    for row, p in enumerate(parsed):
        for name, prob in p["categories"].items():
            col = index.get(name)
            if col is not None:
                matrix[row, col] = prob
    return matrix


def cosine_similarity_matrix(matrix):
    """Pairwise cosine similarity between document rows. Docs with an
    all-zero vector (no parsed categories) get similarity 0 with everyone."""
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    safe_norms = np.where(norms == 0, 1, norms)  # avoid divide-by-zero
    normalized = matrix / safe_norms
    sim = normalized @ normalized.T
    zero_rows = (norms.flatten() == 0)
    sim[zero_rows, :] = 0
    sim[:, zero_rows] = 0
    np.fill_diagonal(sim, 0)  # no self-similarity edges
    return sim


# ---------------------------------------------------------------------------
# Graph construction
# ---------------------------------------------------------------------------

def build_graph(parsed, sim, method="knn", threshold=0.15, k=3):
    """method='knn' (default): connect each document to its top-`k` most
    similar documents (the union of these directed choices, since the graph
    is undirected). Edge count is bounded by k*n regardless of dataset size,
    which is what keeps this readable on large collections.
    method='threshold': connect any pair above `threshold` instead - flexible,
    but on a large/diverse collection a low threshold can produce O(n^2)
    edges and an unreadable "hairball"."""
    G = nx.Graph()

    for i, p in enumerate(parsed):
        G.add_node(
            i,
            title=p["title"],
            difficulty=p["difficulty"],
            confidence=p["confidence"],
            prior_knowledge=p["prior_knowledge"],
            categories=p["categories"],
        )

    n = len(parsed)
    if method == "knn":
        for i in range(n):
            order = np.argsort(-sim[i])  # descending similarity
            added = 0
            for j in order:
                if j == i or sim[i, j] <= 0:
                    continue
                G.add_edge(i, j, weight=float(sim[i, j]))
                added += 1
                if added >= k:
                    break
    else:  # threshold
        for i in range(n):
            for j in range(i + 1, n):
                if sim[i, j] >= threshold:
                    G.add_edge(i, j, weight=float(sim[i, j]))

    return G


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def truncate(text, width=22):
    return textwrap.shorten(text, width=width, placeholder="…")


def compute_layout(G, layout, seed=42):
    """ForceAtlas2 separates dense clusters far more cleanly than spring
    layout once you're past a couple hundred nodes, and it's also faster -
    it's the default for that reason, but spring layout is kept available
    since it can look a little smoother on small graphs."""
    if G.number_of_nodes() == 0:
        return {}
    if layout == "spring":
        return nx.spring_layout(G, weight="weight", seed=seed, k=1.2)
    return nx.forceatlas2_layout(
        G, max_iter=250, seed=seed, weight="weight", scaling_ratio=8.0, gravity=0.3
    )


def detect_communities(G):
    """Greedy modularity communities - used both for optional color-by and
    for choosing a representative node per cluster when there are too many
    documents to label individually."""
    if G.number_of_edges() == 0:
        return [{n} for n in G.nodes]
    return list(nx.community.greedy_modularity_communities(G, weight="weight"))


def cluster_primary_category(G, members):
    """The category that best represents a cluster: whichever category is
    most often each member's own top (highest-probability) category, with
    ties broken by summed probability."""
    counts = Counter()
    prob_sum = defaultdict(float)
    for node in members:
        cats = G.nodes[node].get("categories") or {}
        if not cats:
            continue
        name, prob = next(iter(cats.items()))  # already sorted desc by probability
        counts[name] += 1
        prob_sum[name] += prob
    if not counts:
        return None
    top_count = max(counts.values())
    candidates = [name for name, c in counts.items() if c == top_count]
    return candidates[0] if len(candidates) == 1 else max(candidates, key=lambda n: prob_sum[n])


def compute_cluster_circles(G, pos, communities, min_size=3, spread_percentile=75):
    """One circle per community with at least `min_size` members: centered
    on the member centroid, sized to cover most members (a percentile,
    rather than the absolute max, so a single stray node doesn't blow the
    circle up) with a little padding, and labeled with the cluster's
    primary category. Each circle carries `comm_index` - its position in
    the original `communities` list - so callers can color it to match
    that community's node color exactly, even though small communities
    below `min_size` are skipped here."""
    if not pos:
        return []

    all_pts = np.array(list(pos.values()))
    diag = np.linalg.norm(all_pts.max(axis=0) - all_pts.min(axis=0)) if len(all_pts) > 1 else 1.0
    floor_radius = max(diag * 0.015, 1e-6)

    circles = []
    for comm_index, comm in enumerate(communities):
        if len(comm) < min_size:
            continue
        pts = np.array([pos[n] for n in comm])
        centroid = pts.mean(axis=0)
        dists = np.linalg.norm(pts - centroid, axis=1)
        radius = max(np.percentile(dists, spread_percentile) * 1.08 + diag * 0.01, floor_radius)
        category = cluster_primary_category(G, comm)
        circles.append({
            "comm_index": comm_index,
            "centroid": centroid,
            "radius": radius,
            "label": f"{category or '(no category)'}  ({len(comm)})",
        })
    return circles


def draw_cluster_circles(ax, circles, cmap):
    """Draws largest circles first so smaller, more specific clusters and
    their labels stay visible on top instead of being buried."""
    for c in sorted(circles, key=lambda c: c["radius"], reverse=True):
        color = cmap(c["comm_index"] % 20)
        circle = plt.Circle(c["centroid"], c["radius"], fill=False, linestyle="--",
                            linewidth=1.4, edgecolor=color, alpha=0.9, zorder=1)
        ax.add_patch(circle)
        label_xy = (c["centroid"][0], c["centroid"][1] + c["radius"])
        ax.annotate(
            c["label"], xy=label_xy, ha="center", va="bottom", fontsize=8.5,
            fontweight="bold", color=color,
            bbox=dict(boxstyle="round,pad=0.2", facecolor="white", edgecolor="none", alpha=0.8),
            zorder=5,
        )


def get_node_colors(G, communities, color_by):
    if color_by == "community":
        node_to_comm = {n: ci for ci, comm in enumerate(communities) for n in comm}
        cmap = plt.colormaps["tab20"]
        return [cmap(node_to_comm[n] % 20) for n in G.nodes]
    return [_DIFFICULTY_COLORS.get(G.nodes[n]["difficulty"], "#999999") for n in G.nodes]


# Sequential color scale for difficulty (ordinal: beginner -> expert)
_DIFFICULTY_COLORS = {
    "beginner": "#cfe8ff",
    "intermediate": "#7fb8e8",
    "advanced": "#3a78b5",
    "expert": "#0d2c54",
}


def select_labels(G, communities, max_labels, circles_enabled):
    """Small graphs: label every document, same as before. Large graphs:
    if cluster circles are being drawn, their category labels already
    identify each cluster, so per-node labels are skipped entirely to avoid
    redundant clutter. If circles are disabled, fall back to one
    representative (highest-degree) document title per community instead."""
    n = G.number_of_nodes()
    if n <= max_labels:
        return {node: truncate(G.nodes[node]["title"]) for node in G.nodes}

    if circles_enabled:
        return {}

    strength = dict(G.degree(weight="weight"))
    labels = {}
    for comm in sorted(communities, key=len, reverse=True):
        if len(labels) >= max_labels:
            break
        if len(comm) < 2:
            continue  # skip singleton/isolated "communities" - too many to be useful
        rep = max(comm, key=lambda node: strength[node])
        labels[rep] = f"{truncate(G.nodes[rep]['title'])}  ({len(comm)})"
    return labels


def plot_graph(G, ax, layout="forceatlas2", color_by="auto", max_labels=40,
               show_weights=False, cluster_circles=True, min_circle_size=3):
    if G.number_of_nodes() == 0:
        ax.axis("off")
        ax.set_title("No documents to display")
        return

    n = G.number_of_nodes()
    color_by = ("community" if n > max_labels else "difficulty") if color_by == "auto" else color_by

    pos = compute_layout(G, layout)
    communities = detect_communities(G)
    node_colors = get_node_colors(G, communities, color_by)

    if cluster_circles:
        circles = compute_cluster_circles(G, pos, communities, min_size=min_circle_size)
        draw_cluster_circles(ax, circles, cmap=plt.colormaps["tab20"])

    # Node/edge sizing shrinks as the document count grows, so a few hundred
    # documents don't render as one solid mass of overlapping circles.
    size_scale = max(10, min(300, 2500 / n))
    pk_values = [G.nodes[node]["prior_knowledge"] for node in G.nodes]
    node_sizes = [size_scale * (0.6 + (v if v is not None else 0.3)) for v in pk_values]

    width_scale = max(0.2, min(4.0, 300 / n))
    edge_weights = [G.edges[e]["weight"] for e in G.edges]
    max_w = max(edge_weights) if edge_weights else 1.0
    edge_widths = [width_scale * (0.2 + 0.8 * (w / max_w)) for w in edge_weights]
    edge_alpha = max(0.08, min(0.6, 60 / n))

    nx.draw_networkx_edges(
        G, pos, ax=ax, width=edge_widths, alpha=edge_alpha, edge_color="#555555"
    )
    nx.draw_networkx_nodes(
        G, pos, ax=ax, node_color=node_colors, node_size=node_sizes,
        edgecolors="white", linewidths=0.4 if n <= max_labels else 0,
    )

    labels = select_labels(G, communities, max_labels, circles_enabled=cluster_circles)
    font_size = 7.5 if n <= max_labels else 8
    font_weight = "normal" if n <= max_labels else "bold"
    nx.draw_networkx_labels(G, pos, labels=labels, ax=ax, font_size=font_size,
                            font_weight=font_weight)

    if show_weights:
        if G.number_of_edges() > 200:
            print("Skipping --show-weights: too many edges to annotate legibly "
                  "(use a sparser graph - higher --threshold or lower --k).")
        else:
            edge_labels = {e: f"{G.edges[e]['weight']:.2f}" for e in G.edges}
            nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, ax=ax, font_size=6)

    ax.axis("off")

    if color_by == "community":
        ax.set_title(f"Document similarity graph\n"
                     f"(node size = prior knowledge, color = detected community, "
                     f"{len(communities)} found)")
    else:
        ax.set_title("Document similarity graph\n(node size = prior knowledge, color = difficulty)")
        diff_handles = [
            plt.Line2D([0], [0], marker="o", color="w", label=d,
                       markerfacecolor=_DIFFICULTY_COLORS[d], markersize=10)
            for d in DIFFICULTY_ORDER if d in _DIFFICULTY_COLORS
        ]
        ax.legend(handles=diff_handles, title="Difficulty", loc="upper left",
                  fontsize=8, framealpha=0.9)


def build_similarity_figure(parsed, out_path, method="knn", threshold=0.15, k=3,
                            layout="forceatlas2", color_by="auto", max_labels=40,
                            show_weights=False, cluster_circles=True, min_circle_size=3):
    vocab = build_vocab(parsed)
    if not vocab:
        raise SystemExit("No category names found in the input - can't compute similarity.")

    matrix = build_matrix(parsed, vocab)
    sim = cosine_similarity_matrix(matrix)
    G = build_graph(parsed, sim, method=method, threshold=threshold, k=k)

    n_edges = G.number_of_edges()
    isolated = list(nx.isolates(G))
    if isolated:
        print(f"Note: {len(isolated)} document(s) have no edges above the "
              f"current threshold/k and will appear as unconnected dots.")
    if method == "threshold" and n_edges > 8 * G.number_of_nodes():
        print(f"Note: {n_edges} edges for {G.number_of_nodes()} documents is dense "
              f"- consider raising --threshold, or switch to --method knn, for a "
              f"clearer picture.")

    fig_size = 12 if G.number_of_nodes() <= max_labels else 16
    fig, ax = plt.subplots(figsize=(fig_size, fig_size * 0.85))
    plot_graph(G, ax, layout=layout, color_by=color_by, max_labels=max_labels,
              show_weights=show_weights, cluster_circles=cluster_circles,
              min_circle_size=min_circle_size)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved similarity graph to {out_path}")
    return G


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Visualize document closeness as an undirected graph")
    parser.add_argument("json_path", help="Path to input JSON (array, single object, or JSON-lines)")
    parser.add_argument("--out", default="similarity_graph.png", help="Output image path")
    parser.add_argument("--method", choices=["threshold", "knn"], default="knn",
                        help="knn (default): connect each doc to its --k closest neighbors "
                             "- bounded edge count, safe for large datasets. "
                             "threshold: edge if similarity >= --threshold - can explode on "
                             "large/diverse datasets if the threshold is too low.")
    parser.add_argument("--threshold", type=float, default=0.15,
                        help="Minimum cosine similarity to draw an edge (method=threshold)")
    parser.add_argument("--k", type=int, default=3,
                        help="Number of nearest neighbors per document (method=knn)")
    parser.add_argument("--layout", choices=["forceatlas2", "spring"], default="forceatlas2",
                        help="forceatlas2 (default) separates clusters better at scale; "
                             "spring can look slightly cleaner on small graphs")
    parser.add_argument("--color-by", choices=["auto", "difficulty", "community"], default="auto",
                        help="auto (default): difficulty for small graphs, detected "
                             "community once there are too many documents to label "
                             "individually")
    parser.add_argument("--max-labels", type=int, default=40,
                        help="Above this many documents, only one representative title "
                             "per detected community is labeled (plus its member count) "
                             "instead of every title")
    parser.add_argument("--show-weights", action="store_true",
                        help="Annotate edges with their similarity score (small graphs only)")
    parser.add_argument("--no-cluster-circles", action="store_true",
                        help="Disable the dashed circles drawn around each detected "
                             "cluster (labeled with its primary category)")
    parser.add_argument("--min-circle-size", type=int, default=3,
                        help="Minimum cluster size to draw a circle around (default 3)")
    args = parser.parse_args()

    records = load_records(args.json_path)
    parsed = parse_records(records)

    if not parsed:
        raise SystemExit("No records found in the input file.")

    build_similarity_figure(
        parsed, args.out, method=args.method, threshold=args.threshold, k=args.k,
        layout=args.layout, color_by=args.color_by, max_labels=args.max_labels,
        show_weights=args.show_weights, cluster_circles=not args.no_cluster_circles,
        min_circle_size=args.min_circle_size,
    )


if __name__ == "__main__":
    main()