"""
This code was generated by Claude AI.

prompts:

1) 
Can you write some python code to visualize a json that includes document clusters. 
The json format is: `{"title": "<article_title>", "category1": "<name>:<probability>", "category2":
"<name>:<probability>", "category3": "<name>:<probability>", "confidence": "<low|medium|high>",
"difficulty": "<beginner|intermediate|advanced|expert>", "prior_knowledge": "<range between 0 and 1>"}`

2) 
The new json format is `{
    "title": "<article_title>",
    "<category1>": "<probability>",
    "<category2>": "<probability>",
    "<category3>": "<probability>",
    "confidence": "<low|medium|high>",
    "difficulty": "<beginner|intermediate|advanced|expert>",
    "prior_knowledge": "<float between 0 and 1>"
}` Please adjust the code accordingly

3) 
The new json format includes `"tokens": "<number_of_tokens>`, update the dashboard 
to include the distribution of document sizes for each primary category

visualize_clusters.py

Visualizes document-cluster JSON records of the form:

{
    "title": "<article_title>",
    "<category1>": "<probability>",
    "<category2>": "<probability>",
    "<category3>": "<probability>",
    "confidence": "<low|medium|high>",
    "difficulty": "<beginner|intermediate|advanced|expert>",
    "prior_knowledge": "<float between 0 and 1>",
    "tokens": "<number_of_tokens>"
}

Category names are now arbitrary JSON keys (e.g. "machine_learning": "0.82")
rather than fixed "category1"/"category2"/"category3" fields. Any key that
isn't title/confidence/difficulty/prior_knowledge/tokens is treated as a
category, and a document can have any number of them - not just 3.

Input file can be:
  - a JSON array of such records, or
  - a single JSON object (one record), or
  - a JSON-lines file (one record per line)

Usage:
    python visualize_clusters.py records.json
    python visualize_clusters.py records.json --out dashboard.png
"""

import argparse
import json
from collections import Counter

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

CONFIDENCE_ORDER = ["low", "medium", "high"]
DIFFICULTY_ORDER = ["beginner", "intermediate", "advanced", "expert"]

CONFIDENCE_COLORS = {"low": "#E07B54", "medium": "#F2C14E", "high": "#5B8C5A"}

# Every other key on a record is treated as "<category_name>": "<probability>"
RESERVED_KEYS = {"title", "confidence", "difficulty", "prior_knowledge", "tokens"}


# ---------------------------------------------------------------------------
# Loading & parsing
# ---------------------------------------------------------------------------

def load_records(path):
    """Load records from a JSON array, a single JSON object, or JSON-lines."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read().strip()

    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return [data]
        if isinstance(data, list):
            return data
    except json.JSONDecodeError:
        pass

    # Fall back to JSON-lines (one object per line)
    records = []
    for line in text.splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records


def parse_probability(value):
    """Coerce a probability field (often a string) into a float, or None."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def parse_int(value):
    """Coerce a count field (often a string, sometimes "1234.0") into an
    int, or None."""
    if value is None or value == "":
        return None
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def parse_records(records):
    """Turn raw JSON records into a flat list of dicts ready for plotting.

    Each result has a "categories" dict of {category_name: probability},
    sorted from most to least probable, so "rank 0" is always the
    document's primary category regardless of how many it has."""
    parsed = []
    for r in records:
        item = {
            "title": r.get("title", "Untitled"),
            "confidence": (r.get("confidence") or "unknown").lower(),
            "difficulty": (r.get("difficulty") or "unknown").lower(),
            "prior_knowledge": parse_probability(r.get("prior_knowledge")),
            "tokens": parse_int(r.get("tokens")),
        }

        categories = {}
        for key, value in r.items():
            if key in RESERVED_KEYS:
                continue
            prob = parse_probability(value)
            # key categories should all have the same formatting to avoid issues
            if prob is not None:
                categories[key.lower()] = prob

        item["categories"] = dict(
            sorted(categories.items(), key=lambda kv: kv[1], reverse=True)
        )
        parsed.append(item)
    return parsed


def category_at_rank(item, rank):
    """Return (name, probability) for the rank-th most probable category
    on this document (rank 0 = highest probability), or (None, None)."""
    entries = list(item["categories"].items())
    if rank < len(entries):
        return entries[rank]
    return None, None


def top_category(item):
    """Convenience wrapper: a document's single most probable category."""
    return category_at_rank(item, 0)


# ---------------------------------------------------------------------------
# Individual panel plots
# ---------------------------------------------------------------------------

def primary_category_counts(parsed):
    """How many documents have each category as their top (highest
    probability) pick. Shared by the bar chart and the token-length panel
    so both agree on which categories are "top" and in what order."""
    counter = Counter()
    for p in parsed:
        name, _ = top_category(p)
        if name:
            counter[name] += 1
    return counter


def plot_top_categories(parsed, ax, top_n=10):
    counter = primary_category_counts(parsed)
    common = counter.most_common(top_n)
    if not common:
        ax.axis("off")
        return
    names, counts = zip(*common)
    y = range(len(names))
    ax.barh(y, counts, color="#4C72B0")
    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.invert_yaxis()
    ax.set_xlabel("Document count")
    ax.set_title("Top primary categories")


def plot_confidence_distribution(parsed, ax):
    counter = Counter(p["confidence"] for p in parsed)
    order = [c for c in CONFIDENCE_ORDER if c in counter]
    order += [c for c in counter if c not in CONFIDENCE_ORDER]
    counts = [counter[c] for c in order]
    colors = [CONFIDENCE_COLORS.get(c, "#999999") for c in order]
    ax.bar(order, counts, color=colors)
    ax.set_title("Confidence distribution")
    ax.set_ylabel("Document count")


def plot_difficulty_distribution(parsed, ax):
    counter = Counter(p["difficulty"] for p in parsed)
    order = [d for d in DIFFICULTY_ORDER if d in counter]
    order += [d for d in counter if d not in DIFFICULTY_ORDER]
    counts = [counter[d] for d in order]
    ax.bar(order, counts, color="#7B6D8D")
    ax.set_title("Difficulty distribution")
    ax.set_ylabel("Document count")
    ax.tick_params(axis="x", rotation=20)


def plot_prior_knowledge_vs_difficulty(parsed, ax):
    diff_x = {d: i for i, d in enumerate(DIFFICULTY_ORDER)}
    rng = np.random.default_rng(0)

    for p in parsed:
        if p["prior_knowledge"] is None or p["difficulty"] not in diff_x:
            continue
        x = diff_x[p["difficulty"]] + rng.uniform(-0.15, 0.15)
        y = p["prior_knowledge"]
        color = CONFIDENCE_COLORS.get(p["confidence"], "#999999")
        ax.scatter(x, y, color=color, alpha=0.75, s=45,
                   edgecolor="white", linewidth=0.5)

    ax.set_xticks(range(len(DIFFICULTY_ORDER)))
    ax.set_xticklabels(DIFFICULTY_ORDER, rotation=20)
    ax.set_ylim(-0.05, 1.05)
    ax.set_ylabel("Prior knowledge")
    ax.set_title("Prior knowledge vs. difficulty\n(color = confidence)")

    handles = [mpatches.Patch(color=c, label=l) for l, c in CONFIDENCE_COLORS.items()]
    ax.legend(handles=handles, title="Confidence", fontsize=8, loc="upper right")


def plot_category_probability_box(parsed, ax, max_ranks=5):
    """Box-plots probability by rank (rank 0 = each doc's top category,
    rank 1 = second, etc.), since documents may not all carry the same
    number of categories anymore."""
    max_present = max((len(p["categories"]) for p in parsed), default=0)
    n_ranks = min(max_present, max_ranks)

    data, labels = [], []
    for rank in range(n_ranks):
        vals = [prob for p in parsed
                for _, prob in [category_at_rank(p, rank)] if prob is not None]
        if vals:
            data.append(vals)
            labels.append(f"rank {rank + 1}")

    if not data:
        ax.axis("off")
        return
    try:
        ax.boxplot(data, tick_labels=labels)  # matplotlib >= 3.9
    except TypeError:
        ax.boxplot(data, labels=labels)  # matplotlib < 3.9
    ax.set_ylabel("Probability")
    ax.set_title("Probability spread by category rank\n(rank 1 = each doc's top category)")


def plot_tokens_by_category(parsed, ax, top_n=10):
    """Box-plots document length (tokens) for each of the most common
    primary categories, so you can see e.g. whether "history" articles run
    much longer than "mathematics" articles. Uses the same top-N category
    selection/order as plot_top_categories for easy cross-reference."""
    counter = primary_category_counts(parsed)
    top_names = [name for name, _ in counter.most_common(top_n)]

    # Precompute (top category, tokens) once per doc rather than re-deriving
    # top_category() inside a nested loop over every candidate category.
    doc_top_tokens = [(top_category(p)[0], p["tokens"]) for p in parsed]

    data, labels = [], []
    for name in top_names:
        vals = [tok for cat, tok in doc_top_tokens if cat == name and tok is not None]
        if vals:
            data.append(vals)
            labels.append(name)

    if not data:
        ax.axis("off")
        return
    try:
        ax.boxplot(data, tick_labels=labels, vert=False)  # matplotlib >= 3.9
    except TypeError:
        ax.boxplot(data, labels=labels, vert=False)  # matplotlib < 3.9
    ax.invert_yaxis()  # largest/most common category on top, matching the bar chart
    ax.set_xlabel("Tokens (document length)")
    ax.set_title(f"Document length by top {len(labels)} categories")


def plot_summary_text(parsed, ax):
    ax.axis("off")
    n = len(parsed)
    avg_pk = np.mean([p["prior_knowledge"] for p in parsed if p["prior_knowledge"] is not None])
    avg_tokens = np.mean([p["tokens"] for p in parsed if p["tokens"] is not None])
    n_categories = len({top_category(p)[0] for p in parsed if top_category(p)[0]})
    lines = [
        f"Documents: {n}",
        f"Distinct primary categories: {n_categories}",
        f"Avg. prior knowledge: {avg_pk:.2f}" if not np.isnan(avg_pk) else "Avg. prior knowledge: n/a",
        f"Avg. tokens: {avg_tokens:.0f}" if not np.isnan(avg_tokens) else "Avg. tokens: n/a",
    ]
    ax.text(0.05, 0.8, "\n".join(lines), fontsize=12, va="top",
            family="monospace", transform=ax.transAxes)
    ax.set_title("Summary")


# ---------------------------------------------------------------------------
# Dashboard assembly
# ---------------------------------------------------------------------------

def build_dashboard(parsed, out_path):
    fig, axes = plt.subplots(2, 4, figsize=(24, 10))

    plot_top_categories(parsed, axes[0, 0])
    plot_confidence_distribution(parsed, axes[0, 1])
    plot_difficulty_distribution(parsed, axes[0, 2])
    plot_tokens_by_category(parsed, axes[0, 3])
    plot_prior_knowledge_vs_difficulty(parsed, axes[1, 0])
    plot_category_probability_box(parsed, axes[1, 1])
    plot_summary_text(parsed, axes[1, 2])
    axes[1, 3].axis("off")

    fig.suptitle("Document Cluster Overview", fontsize=16, fontweight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved dashboard to {out_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Visualize document cluster JSON")
    parser.add_argument("json_path", help="Path to input JSON (array, single object, or JSON-lines)")
    parser.add_argument("--out", default="cluster_dashboard.png", help="Output image path")
    args = parser.parse_args()

    records = load_records(args.json_path)
    parsed = parse_records(records)

    if not parsed:
        raise SystemExit("No records found in the input file.")

    build_dashboard(parsed, args.out)


if __name__ == "__main__":
    main()